#!/bin/bash
echo @@@making standalone versions!
sudo yum update -y
echo @@@downloading maven
sudo wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo -O /etc/yum.repos.d/epel-apache-maven.repo
sudo sed -i s/\$releasever/6/g /etc/yum.repos.d/epel-apache-maven.repo
sudo yum install -y apache-maven
mvn -version

echo @@@installing jdk 1.8
sudo yum install java-1.8.0-openjdk-devel.x86_64 -y

wget https://s3-us-west-2.amazonaws.com/dsps192assignment1/assignment1.zip
unzip assignment1.zip
cd assignment1
sed -i 's/Manager/Worker/g' pom.xml
sed -i 's/LocalApp/Worker/g' pom.xml
mvn clean compile assembly:single
cd target
mv assignment1-0.0.1-SNAPSHOT-jar-with-dependencies.jar worker.jar
aws s3 cp worker.jar s3://dsps192assignment1 --acl public-read 

cd ..

sed -i 's/Worker/Manager/g' pom.xml

mvn clean compile assembly:single
cd target
mv assignment1-0.0.1-SNAPSHOT-jar-with-dependencies.jar manager.jar
aws s3 cp manager.jar s3://dsps192assignment1 --acl public-read

cd ..

sed -i 's/Manager/LocalApp/g' pom.xml

mvn clean compile assembly:single
cd target
mv assignment1-0.0.1-SNAPSHOT-jar-with-dependencies.jar localApp.jar
aws s3 cp localApp.jar s3://dsps192assignment1 --acl public-read 
echo @@@DONE!
